name: Telegram bot sync

on:
  workflow_dispatch: # اجرای دستی
  schedule:
    - cron: "0 * * * *" # هر ساعت در دقیقه 0

jobs:
  sync_messages:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Start Flow
        run: echo "Starting Telegram to Rubika message sync flow..."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5 # استفاده از نسخه جدیدتر setup-python
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4


      - name: Run Telegram Bot Script
        run: |
          echo "Running telegram_bot.py..."
          python telegram_bot.py
          echo "Script finished."
    fi

      # - name: Wait 5 seconds
      #   run: sleep 5

      - name: 🏁 Flow completed successfully
        run: echo "Flow finished successfully."
